# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require 'date'




names = [
    "Billy",
    "Samantha",
    "James",
    "Sarah",
    "Peter",
    "Bobby",
    "Lilly",
    "Jenefer",
    "Ameright",
    "AmyTale",
    "AnhartGutsy",
    "Annipol",
    "Arnhoto",
    "Aspri",
    "Awarmajo",
    "Beaster",
    "BeatKai",
    "BeeFamous",
    "BeeTricky",
    "BloggerSan",
    "Bornda",
    "BornDiddy",
    "BrightTracker",
    "Brunhyama",
    "BuffyTown",
    "BulletinBroadcast",
    "CartTeam",
    "Casexylo",
    "Catawal",
    "Censific",
    "CornyTins",
    "Degelida",
    "Deluxedn",
    "Deskil",
    "DeskStorm",
    "Diaryco",
    "Dollow",
    "Endevra",
    "Eponyse",
    "Estinger",
    "ExpertDj",
    "Fostext",
    "Fromanico",
    "Futurcidi",
    "GambitVamp",
    "Genusten",
    "Gingeriddi",
    "Gurlyri",
    "Habiarybo",
    "Hippooder",
    "Hockeyni",
    "Horrayno",
    "Hyperol",
    "IfallGutsy",
    "IneedUpdate",
    "Initerac",
    "Invadeca",
    "Janhe",
    "Jubiianes",
    "KnotAsh",
    "Kroolab",
    "Labson",
    "LightTy",
    "LikeSincere",
    "Linxitre",
    "LuvWitty",
    "Magazinetidi",
    "MagicChone",
    "Markkirb",
    "Megsat",
    "Mexicom",
    "Mitokomat",
    "MuraSheer",
    "Musickimb",
    "Newskina",
    "NoteAra",
    "Peachlo",
    "Pemcopton",
    "PhatDubya",
    "Pinchin",
    "Ployerry",
    "Powervisa",
    "Puppyfo",
    "Quicksoun",
    "Ridatafo",
    "SandBlonde",
    "Shmoeci",
    "SlipkWeekly",
    "Stasiati",
    "Stoople",
    "TalesTrimble",
    "TaraLedger",
    "TasticGroup",
    "Terramput",
    "TightMercy",
    "Tinkerli",
    "Tipsag",
    "Toontilm",
    "Tracker",
    "TreasureKnight",
    "Tuckhora",
    "Uplestom",
    "Vanatery",
    "VashPerson",
    "Waldribar",
    "WannaIfall",
    "WindGazette",
    "Womanettr",
    "Chad"
]



ingredients = [    #552
	"Chicken",
	"Salmon",
	"Beef",
	"Pork",
	"Avocado",
	"Apple Cider Vinegar",
	"Asparagus",
	"Aubergine",
	"Baby Plum Tomatoes",
	"Bacon",
	"Baking Powder",
	"Balsamic Vinegar",
	"Basil",
	"Basil Leaves",
	"Basmati Rice",
	"Bay Leaf",
	"Bay Leaves",
	"Beef Brisket",
	"Beef Fillet",
	"Beef Gravy",
	"Beef Stock",
	"Bicarbonate Of Soda",
	"Biryani Masala",
	"Black Pepper",
	"Black Treacle",
	"Borlotti Beans",
	"Bowtie Pasta",
	"Bramley Apples",
	"Brandy",
	"Bread",
	"Breadcrumbs",
	"Broccoli",
	"Brown Lentils",
	"Brown Rice",
	"Brown Sugar",
	"Butter",
	"Cacao",
	"Cajun",
	"Canned Tomatoes",
	"Cannellini Beans",
	"Cardamom",
	"Carrots",
	"Cashew Nuts",
	"Cashews",
	"Caster Sugar",
	"Cayenne Pepper",
	"Celeriac",
	"Celery",
	"Celery Salt",
	"Challots",
	"Charlotte Potatoes",
	"Cheddar Cheese",
	"Cheese",
	"Cheese Curds",
	"Cherry Tomatoes",
	"Chestnut Mushroom",
	"Chicken Breast",
	"Chicken Breasts",
	"Chicken Legs",
	"Chicken Stock",
	"Chicken Thighs",
	"Chickpeas",
	"Chili Powder",
	"Chilled Butter",
	"Chilli",
	"Chilli Powder",
	"Chinese Broccoli",
	"Chocolate Chips",
	"Chopped Onion",
	"Chopped Parsley",
	"Chopped Tomatoes",
	"Chorizo",
	"Christmas Pudding",
	"Cilantro",
	"Cinnamon",
	"Cinnamon Stick",
	"Cloves",
	"Coco Sugar",
	"Cocoa",
	"Coconut Cream",
	"Coconut Milk",
	"Colby Jack Cheese",
	"Cold Water",
	"Condensed Milk",
	"Coriander",
	"Coriander Leaves",
	"Coriander Seeds",
	"Corn Tortillas",
	"Cornstarch",
	"Cream",
	"Creme Fraiche",
	"Cubed Feta Cheese",
	"Cucumber",
	"Cumin",
	"Cumin Seeds",
	"Curry Powder",
	"Dark Brown Sugar",
	"Dark Soft Brown Sugar",
	"Dark Soy Sauce",
	"Demerara Sugar",
	"Diced Tomatoes",
	"Digestive Biscuits",
	"Dill",
	"Doner Meat",
	"Double Cream",
	"Dried Oregano",
	"Dry White Wine",
	"Egg Plants",
	"Egg Rolls",
	"Egg White",
	"Egg Yolks",
	"Eggs",
	"Enchilada Sauce",
	"English Mustard",
	"Extra Virgin Olive Oil",
	"Fajita Seasoning",
	"Farfalle",
	"Fennel",
	"Fennel Bulb",
	"Fennel Seeds",
	"Fenugreek",
	"Feta",
	"Fish Sauce",
	"Flaked Almonds",
	"Flax Eggs",
	"Flour",
	"Flour Tortilla",
	"Floury Potatoes",
	"Free-range Egg, Beaten",
	"Free-range Eggs, Beaten",
	"French Lentils",
	"Fresh Basil",
	"Fresh Thyme",
	"Freshly Chopped Parsley",
	"Fries",
	"Full Fat Yogurt",
	"Garam Masala",
	"Garlic",
	"Garlic Clove",
	"Garlic Powder",
	"Garlic Sauce",
	"Ghee",
	"Ginger",
	"Ginger Cordial",
	"Ginger Garlic Paste",
	"Ginger Paste",
	"Golden Syrup",
	"Gouda Cheese",
	"Granulated Sugar",
	"Grape Tomatoes",
	"Greek Yogurt",
	"Green Beans",
	"Green Chilli",
	"Green Olives",
	"Green Red Lentils",
	"Green Salsa",
	"Ground Almonds",
	"Ground Cumin",
	"Ground Ginger",
	"Gruyère",
	"Hard Taco Shells",
	"Harissa Spice",
	"Heavy Cream",
	"Honey",
	"Horseradish",
	"Hot Beef Stock",
	"Hotsauce",
	"Ice Cream",
	"Italian Fennel Sausages",
	"Italian Seasoning",
	"Jalapeno",
	"Jasmine Rice",
	"Jerusalem Artichokes",
	"Kale",
	"Khus Khus",
	"King Prawns",
	"Kosher Salt",
	"Lamb",
	"Lamb Loin Chops",
	"Lamb Mince",
	"Lasagne Sheets",
	"Lean Minced Beef",
	"Leek",
	"Lemon",
	"Lemon Juice",
	"Lemon Zest",
	"Lemons",
	"Lettuce",
	"Lime",
	"Little Gem Lettuce",
	"Macaroni",
	"Mackerel",
	"Madras Paste",
	"Marjoram",
	"Massaman Curry Paste",
	"Medjool Dates",
	"Meringue Nests",
	"Milk",
	"Minced Garlic",
	"Miniature Marshmallows",
	"Mint",
	"Monterey Jack Cheese",
	"Mozzarella Balls",
	"Muscovado Sugar",
	"Mushrooms",
	"Mustard",
	"Mustard Powder",
	"Mustard Seeds",
	"Nutmeg",
	"Oil",
	"Olive Oil",
	"Onion Salt",
	"Onions",
	"Orange",
	"Orange Zest",
	"Oregano",
	"Oyster Sauce",
	"Paprika",
	"Parma Ham",
	"Parmesan",
	"Parmesan Cheese",
	"Parmigiano-reggiano",
	"Parsley",
	"Peanut Butter",
	"Peanut Oil",
	"Peanuts",
	"Peas",
	"Pecorino",
	"Penne Rigate",
	"Pepper",
	"Pine Nuts",
	"Pitted Black Olives",
	"Plain Chocolate",
	"Plain Flour",
	"Plum Tomatoes",
	"Potato Starch",
	"Potatoes",
	"Prawns",
	"Puff Pastry",
	"Raspberry Jam",
	"Raw King Prawns",
	"Red Chile Flakes",
	"Red Chilli",
	"Red Chilli Powder",
	"Red Onions",
	"Red Pepper",
	"Red Pepper Flakes",
	"Red Wine",
	"Refried Beans",
	"Rice",
	"Rice Noodles",
	"Rice Stick Noodles",
	"Rice Vermicelli",
	"Rigatoni",
	"Rocket",
	"Rolled Oats",
	"Rosemary",
	"Saffron",
	"Sage",
	"Sake",
	"Salsa",
	"Salt",
	"Salted Butter",
	"Sausages",
	"Sea Salt",
	"Self-raising Flour",
	"Semi-skimmed Milk",
	"Sesame Seed",
	"Shallots",
	"Shredded Mexican Cheese",
	"Shredded Monterey Jack Cheese",
	"Small Potatoes",
	"Smoked Paprika",
	"Smoky Paprika",
	"Sour Cream",
	"Soy Sauce",
	"Soya Milk",
	"Spaghetti",
	"Spinach",
	"Spring Onions",
	"Squash",
	"Stir-fry Vegetables",
	"Strawberries",
	"Sugar",
	"Sultanas",
	"Sunflower Oil",
	"Tamarind Ball",
	"Tamarind Paste",
	"Thai Fish Sauce",
	"Thai Green Curry Paste",
	"Thai Red Curry Paste",
	"Thyme",
	"Tomato Ketchup",
	"Tomato Puree",
	"Tomatoes",
	"Toor Dal",
	"Tuna",
	"Turmeric",
	"Turmeric Powder",
	"Turnips",
	"Vanilla",
	"Vanilla Extract",
	"Veal",
	"Vegan Butter",
	"Vegetable Oil",
	"Vegetable Stock",
	"Vegetable Stock Cube",
	"Vinaigrette Dressing",
	"Vine Leaves",
	"Vinegar",
	"Water",
	"White Chocolate Chips",
	"White Fish",
	"White Fish Fillets",
	"White Vinegar",
	"White Wine",
	"Whole Milk",
	"Whole Wheat",
	"Wholegrain Bread",
	"Worcestershire Sauce",
	"Yogurt",
	"Zucchini",
	"Pretzels",
	"Cream Cheese",
	"Icing Sugar",
	"Toffee Popcorn",
	"Caramel",
	"Caramel Sauce",
	"Tagliatelle",
	"Fettuccine",
	"Clotted Cream",
	"Corn Flour",
	"Mussels",
	"Fideo",
	"Monkfish",
	"Vermicelli Pasta",
	"Baby Squid",
	"Squid",
	"Fish Stock",
	"Pilchards",
	"Black Olives",
	"Onion",
	"Tomato",
	"Duck",
	"Duck Legs",
	"Chicken Stock Cube",
	"Pappardelle Pasta",
	"Paccheri Pasta",
	"Linguine Pasta",
	"Sugar Snap Peas",
	"Crusty Bread",
	"Fromage Frais",
	"Clams",
	"Passata",
	"Rapeseed Oil",
	"Stilton Cheese",
	"Lamb Leg",
	"Lamb Shoulder",
	"Apricot",
	"Butternut Squash",
	"Couscous",
	"Minced Beef",
	"Turkey Mince",
	"Barbeque Sauce",
	"Sweetcorn",
	"Goose Fat",
	"Duck Fat",
	"Fennel",
	"Red Wine Vinegar",
	"Haricot Beans",
	"Rosemary",
	"Butter Beans",
	"Pinto Beans",
	"Tomato Sauce",
	"Tomato Sauce",
	"Mascarpone",
	"Mozzarella",
	"Ricotta",
	"Dried Apricots",
	"Capers",
	"Banana",
	"Raspberries",
	"Blueberries",
	"Walnuts",
	"Pecan Nuts",
	"Maple Syrup",
	"Light Brown Soft Sugar",
	"Dark Brown Soft Sugar",
	"Dark Chocolate Chips",
	"Milk Chocolate",
	"Dark Chocolate",
	"Pumpkin",
	"Shortcrust Pastry",
	"Peanut Cookies",
	"Gelatine Leafs",
	"Peanut Brittle",
	"Peaches",
	"Yellow Pepper",
	"Green Pepper",
	"Courgettes",
	"Tinned Tomatos",
	"Chestnuts",
	"Wild Mushrooms",
	"Truffle Oil",
	"Paneer",
	"Naan Bread",
	"Lentils",
	"Roasted Vegetables",
	"Kidney Beans",
	"Mixed Grain",
	"Tahini",
	"Tortillas",
	"Udon Noodles",
	"Cabbage",
	"Shiitake Mushrooms",
	"Mirin",
	"Sesame Seed Oil",
	"Baguette",
	"Vine Tomatoes",
	"Suet",
	"Swede",
	"Ham",
	"Oysters",
	"Stout",
	"Lard",
	"Lamb Kidney",
	"Beef Kidney",
	"Haddock",
	"Smoked Haddock",
	"Brussels Sprouts",
	"Raisins",
	"Currants",
	"Custard",
	"Mixed Peel",
	"Redcurrants",
	"Blackberries",
	"Hazlenuts",
	"Braeburn Apples",
	"Red Food Colouring",
	"Pink Food Colouring",
	"Blue Food Colouring",
	"Yellow Food Colouring",
	"Apricot Jam",
	"Marzipan",
	"Almonds",
	"Black Pudding",
	"Baked Beans",
	"White Flour",
	"Yeast",
	"Fruit Mix",
	"Dried Fruit",
	"Cherry",
	"Glace Cherry",
	"Treacle",
	"Oatmeal",
	"Oats",
	"Egg",
	"Beef Shin",
	"Bouquet Garni",
	"Single Cream",
	"Red Wine Jelly",
	"Apples",
	"Goats Cheese",
	"Prosciutto",
	"Unsalted Butter",
	"Brie",
	"Tarragon Leaves",
	"Chives",
	"Pears",
	"White Chocolate",
	"Star Anise",
	"Tiger Prawns",
	"Custard Powder",
	"Desiccated Coconut",
	"Frozen Peas",
	"Minced Pork",
	"Creamed Corn",
	"Sun-Dried Tomatoes",
	"Dijon Mustard",
	"Tabasco Sauce",
	"Canola Oil",
	"Cod",
	"Salt Cod",
	"Ackee",
	"Jerk",
	"Ground Beef",
	"Baby Aubergine",
	"Paella Rice",
	"Scotch Bonnet",
	"Oxtail",
	"Broad Beans",
	"Red Snapper",
	"Malt Vinegar",
	"Rice Vinegar",
	"Water Chestnut",
	"Tofu",
	"Doubanjiang",
	"Fermented Black Beans",
	"Scallions",
	"Sichuan Pepper",
	"Wonton Skin",
	"Starch",
	"Rice wine",
	"Cooking wine",
	"Duck Sauce",
	"Gochujang",
	"Bean Sprouts",
	"Noodles",
	"Wood Ear Mushrooms",
	"Dark Rum",
	"Light Rum",
	"Rum",
	"English Muffins",
	"Muffins",
	"White Wine Vinegar",
	"Smoked Salmon",
	"Mars Bar",
	"Rice Krispies",
	"Ancho Chillies",
	"Almond Milk",
	"Allspice",
	"Almond Extract",
	"Tripe",
	"Goat Meat",
	"Black Beans",
	"Anchovy Fillet",
	"Ras el hanout",
	"Filo Pastry",
	"Orange Blossom Water",
	"Candied Peel",
	"Grand Marnier",
	"Sherry",
	"Rose water",
	"Mixed Spice",
	"Mincemeat",
	"Sweet Potatoes",
	"Bread Rolls",
	"Bun",
	"Potatoe Buns",
	"Ground Pork",
	"Pork Chops",
	"Yukon Gold Potatoes",
	"Yellow Onion",
	"Beef Stock Concentrate",
	"Chicken Stock Concentrate",
	"Persian Cucumber",
	"Mayonnaise",
	"Sriracha",
	"Rhubarb",
	"Pita Bread",
	"Bulgur Wheat",
	"Quinoa"
]



recipe = {
    names: [
        "Apple Frangipan Tart",
        "Apple & Blackberry Crumble",
        "Bakewell tart",
        "Bread and Butter Pudding",
        "Beef Wellington",
        "Baingan Bharta",
        "Beef Brisket Pot Roast",
        "Beef Sunday Roast",
        "Braised Beef Chilli",
        "Beef stroganoff",
        "Broccoli & Stilton soup",
        "Bean & Sausage Hotpot",
        "Banana Pancakes",
        "Beef Dumpling Stew",
        "Beef and Mustard Pie",
        "Beef and Oyster pie",
        "Blackberry Fool",
        "Battenberg Cake",
        "Beef Bourguignon",
        "Brie wrapped in prosciutto & brioche",
        "Boulangère Potatoes",
        "BeaverTails",
        "Brown Stew Chicken",
        "Beef Lo Mein",
        "Baked salmon with fennel & tomatoes",
        "Budino Di Ricotta",
        "Breakfast Potatoes",
        "Bitterballen (Dutch meatballs)",
        "BBQ Pork Sloppy Joes with Pickled Onion & Sweet Potato Wedges",
        "Beef Banh Mi Bowls with Sriracha Mayo, Carrot & Pickled Cucumber",
        "Chocolate Gateau",
        "Chicken Enchilada Casserole",
        "Cream Cheese Tart",
        "Christmas Pudding Flapjack",
        "Chicken Handi",
        "Chicken Alfredo Primavera",
        "Chicken Fajita Mac and Cheese",
        "Cajun spiced fish tacos",
        "Crock Pot Chicken Baked Tacos",
        "Chicken Karaage",
        "Coq au vin",
        "Chilli prawn linguine",
        "Clam chowder",
        "Creamy Tomato Soup",
        "Chicken & mushroom Hotpot",
        "Chicken Couscous",
        "Chocolate Avocado Mousse",
        "Choc Chip Pecan Pie",
        "Chocolate Raspberry Brownies",
        "Chickpea Fajitas",
        "Chicken Ham and Leek Pie",
        "Chicken Parmentier",
        "Carrot Cake",
        "Chelsea Buns",
        "Chocolate Souffle",
        "Chinon Apple Tarts",
        "Chicken Marengo",
        "Canadian Butter Tarts",
        "Chicken Basquaise",
        "Callaloo Jamaican Style",
        "Chicken Congee",
        "Chocolate Caramel Crispy",
        "Chakchouka ",
        "Cashew Ghoriba Biscuits",
        "Corba",
        "Christmas Pudding Trifle",
        "Classic Christmas pudding",
        "Christmas cake",
        "Corned Beef and Cabbage",
        "Crispy Sausages and Greens",
        "Chicken Quinoa Greek Salad",
        "Dal fry",
        "Dundee cake",
        "Duck Confit",
        "Eton Mess",
        "Eccles Cakes",
        "English Breakfast",
        "Escovitch Fish",
        "Egg Drop Soup",
        "Fish pie",
        "French Lentils With Garlic and Thyme",
        "Fettucine alfredo",
        "Full English Breakfast",
        "French Onion Soup",
        "Flamiche",
        "French Omelette",
        "Fish Stew with Rouille",
        "Fennel Dauphinoise",
        "Fruit and Cream Cheese Breakfast Pastries",
        "French Onion Chicken with Roasted Carrots & Mashed Potatoes",
        "Garides Saganaki",
        "Grilled Mac and Cheese Sandwich",
        "General Tso's Chicken",
        "Gigantes Plaki",
        "Honey Teriyaki Salmon",
        "Hot Chocolate Fudge",
        "Hot and Sour Soup",
        "Home-made Mandazi",
        "Honey Balsamic Chicken with Crispy Broccoli & Potatoes",
        "Honey Yogurt Cheesecake",
        "Irish stew",
        "Jam Roly-Poly",
        "Jerk chicken with rice & peas",
        "Jamaican Beef Patties",
        "Kapsalon",
        "Kentucky Fried Chicken",
        "Katsu Chicken curry",
        "Key Lime Pie",
        "Kidney Bean Curry",
        "Kedgeree",
        "Kung Pao Chicken",
        "Kung Po Prawns",
        "Kafteji",
        "Keleya Zaara",
        "Kumpir",
        "Lamb tomato and sweet spices",
        "Lamb Biryani",
        "Lamb Rogan josh",
        "Laksa King Prawn Noodles",
        "Lamb Tagine",
        "Lasagne",
        "Lamb and Potato pie",
        "Lancashire hotpot",
        "Leblebi Soup",
        "Lasagna Sandwiches",
        "Lamb and Lemon Souvlaki",
        "Lamb Tzatziki Burgers",
        "Mediterranean Pasta Salad",
        "Massaman Beef curry",
        "Mushroom & Chestnut Rotolo",
        "Matar Paneer",
        "Minced Beef Pie",
        "McSinghs Scotch pie",
        "Madeira Cake",
        "Montreal Smoked Meat",
        "Ma Po Tofu",
        "Mbuzi Choma (Roasted Goat)",
        "Mince Pies",
        "Moussaka",
        "Nutty Chicken Curry",
        "New York cheesecake",
        "Nanaimo Bars",
        "Osso Buco alla Milanese",
        "Oxtail with broad beans",
        "Pad See Ew",
        "Potato Gratin with Chicken",
        "Poutine",
        "Pilchard puttanesca",
        "Pork Cassoulet",
        "Pancakes",
        "Pumpkin Pie",
        "Peanut Butter Cheesecake",
        "Peach & Blueberry Grunt",
        "Parkin Cake",
        "Pear Tarte Tatin",
        "Provençal Omelette Cake",
        "Prawn & Fennel Bisque",
        "Pate Chinois",
        "Pouding chomeur",
        "Peanut Butter Cookies",
        "Rigatoni with fennel sausage sauce",
        "Rocky Road Fudge",
        "Recheado Masala Fish",
        "Ribollita",
        "Roasted Eggplant With Tahini, Pine Nuts, and Lentils",
        "Rock Cakes",
        "Ratatouille",
        "Rappie Pie",
        "Red Peas Soup",
        "Roast fennel and aubergine paella",
        "Spaghetti Bolognese",
        "Spicy Arrabiata Penne",
        "Smoky Lentil Chili with Squash",
        "Sticky Toffee Pudding Ultimate",
        "Spicy North African Potato Salad",
        "Stovetop Eggplant With Harissa, Chickpeas, and Cumin Yogurt",
        "Salmon Prawn Risotto",
        "Salted Caramel Cheescake",
        "Seafood fideuà",
        "Spinach & Ricotta Cannelloni",
        "Squash linguine",
        "Spanish Tortilla",
        "Steak and Kidney Pie",
        "Sticky Toffee Pudding",
        "Spotted Dick",
        "Summer Pudding",
        "Summer Pistou",
        "Split Pea Soup",
        "Sugar Pie",
        "Steak Diane",
        "Saltfish and Ackee",
        "Sweet and Sour Pork",
        "Szechuan Beef",
        "Shrimp Chow Fun",
        "Salmon Avocado Salad",
        "Salmon Eggs Eggs Benedict",
        "Shakshuka",
        "Smoked Haddock Kedgeree",
        "Stamppot",
        "Snert (Dutch Split Pea Soup)",
        "Spaghetti alla Carbonara",
        "Soy-Glazed Meatloaves with Wasabi Mashed Potatoes & Roasted Carrots",
        "Skillet Apple Pork Chops with Roasted Sweet Potatoes & Zucchini",
        "Strawberry Rhubarb Pie",
        "Stuffed Lamb Tomatoes",
        "Teriyaki Chicken Casserole",
        "Tandoori chicken",
        "Thai Green Curry",
        "Toad In The Hole",
        "Turkey Meatloaf",
        "Tuna Nicoise",
        "Tahini Lentils",
        "Three Fish Pie",
        "Treacle Tart",
        "Tarte Tatin",
        "Three-cheese souffles",
        "Tourtiere",
        "Timbits",
        "Tunisian Orange Cake",
        "Tunisian Lamb Soup",
        "Tuna and Egg Briks",
        "Vegan Lasagna",
        "Vegan Chocolate Cake",
        "Vietnamese Grilled Pork (bun-thit-nuong)",
        "Venetian Duck Ragu",
        "Vegetarian Casserole",
        "Vegetarian Chilli",
        "Vegetable Shepherd’s Pie",
        "White chocolate creme brulee",
        "Wontons",
        "Yaki Udon"
    ],
    description: "\
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sed dui efficitur, pulvinar odio a, commodo tellus. In enim massa, faucibus et porta a, rutrum nec mauris. Morbi tincidunt mi vel dolor fringilla convallis. Fusce fringilla eros convallis nisi pretium commodo. Vivamus laoreet gravida quam, nec accumsan risus sodales vitae. Curabitur non nulla efficitur, commodo ipsum in, egestas urna. Donec condimentum nunc ut augue hendrerit, eu posuere urna mollis. Integer tempus condimentum elit. Nam vehicula ligula lorem, a gravida elit fringilla sed. In bibendum condimentum dui, in posuere lorem rhoncus sit amet. Nunc accumsan sem quis risus faucibus maximus. Nam iaculis bibendum mauris. Etiam tincidunt in felis sed porttitor.\

    Sed eget turpis orci. Praesent vel hendrerit lectus. Donec non orci at dui feugiat efficitur. Proin elementum, nisi a gravida ullamcorper, nunc nulla suscipit ipsum, quis aliquet massa erat quis urna. Donec tempus vitae eros at pulvinar. Phasellus id finibus justo. Ut sed mi nec orci lobortis pharetra. Suspendisse fringilla fermentum ante sed placerat. Nullam maximus mollis metus vitae dapibus.\

    Integer varius congue orci, id euismod urna cursus vel. Praesent iaculis orci tortor, porttitor faucibus purus vehicula nec. Integer nec orci vitae tortor tincidunt vulputate. Nunc eu nisl nisl. Nunc lobortis pulvinar faucibus. Nam augue massa, varius nec enim vel, ultricies blandit quam. Phasellus placerat dui vel ipsum auctor, at porta diam pharetra. Pellentesque vulputate, leo elementum venenatis iaculis, odio nulla tempor quam, et lacinia quam felis et eros. In commodo egestas metus a vulputate. Etiam ultricies ipsum vel elit luctus, nec congue lorem consectetur. Nulla nec augue dui. Ut risus massa, mattis sit amet felis nec, egestas tempus leo. Nam ut pretium metus. Vivamus non dapibus enim, in sagittis ante. Suspendisse non euismod nulla. Sed et mi porttitor, congue lacus eu, sagittis ex.\

    Duis sit amet massa sagittis, sagittis nisl eu, rutrum ligula. Curabitur erat dolor, feugiat quis facilisis ac, tincidunt quis nisi. Nulla mattis faucibus bibendum. Integer vel sapien libero. Mauris faucibus odio nec quam consequat, a scelerisque mi aliquam. Morbi rutrum lorem in dui feugiat malesuada. Donec feugiat blandit ante vel gravida. Proin eget condimentum lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis imperdiet ipsum sed velit congue, ac maximus quam convallis. Praesent nibh lorem, semper ut sagittis id, viverra eget erat. Cras condimentum massa ac velit iaculis sodales. In lacinia leo sed odio suscipit fermentum. Ut quis massa nec turpis maximus auctor eu eget leo. Phasellus iaculis nisi nibh, eu varius nunc elementum ut.\

    Phasellus mattis auctor eros. In blandit eget arcu at elementum. Integer et ipsum nec magna auctor dignissim in eget lacus. Sed euismod augue in risus varius molestie. Donec pharetra odio vitae massa tincidunt luctus. Nulla ac nibh ligula. Proin quam lorem, pellentesque sit amet diam quis, vulputate tincidunt lacus. Phasellus at urna in risus cursus vestibulum. Nullam vestibulum lobortis suscipit. Curabitur ut condimentum neque, eget sodales turpis. Maecenas sodales libero sit amet arcu laoreet, sit amet aliquet nibh sagittis. Morbi interdum erat sed justo tincidunt semper.
    "
}


units = [
    "","",
    "kg","kg",
    "lbs","lbs",
    "pintches",
    "tsp",
    "ml"
]


storage = [
    "Bin",
    "Pantry",
    "Cupboard",
    "Fridge",
    "Cabinet",
    "Ouside Barrel",
    "The Stash Behind the TV",
    "The Bottom of the River",
    "Sally's Kitchen Cabinet",
    "Under my Sister's Bed"
]


def random_date
    
    month = rand(12)+1
    day = rand(28)+1
    str_date = "2020-#{month}-#{day}"
    DateTime.parse(str_date)
    
    
=begin
    formatted_date = date.strftime('%a %b %d %Y')
    puts formatted_date
=end
end


desc_array = recipe[:description].split('.')






# =>    Pantry Item
#
#        - name         :  names[]
#        - quantity     :  rand(int)
#        - units        :  units[]
#
#        - storage_bin  :  storage[]
#
#        - when_bought  :  random_date()   <datetime>
#        - exp_date     :  random_date()^  + rand(int)   <datetime>
#
#        - min_item     :  rand(int)
#        - max_item     :  rand(int)^  + rand(int)




# =>    UserRecipe

#        - name         :  names[] 
#        - description  :  recipe[:description].split('.')   <<random ammount of sentences
# =>    est_time



# => =>   Ingredient

#           - name         :  names[] 
#           - amount       :  rand(int)
#           - units        :  units[]



# => =>   Instruction

#           - step :   recipe[:description].split('.')[rand(int)] ~ish






#puts recipe[:description].split('.')
#puts [(rand(60)+1)].map(&:to_a).flatten


=begin
200.times do |number|
    if ( rand(60)+1 == 60 )
        puts "60"
    elsif ( rand(60)+1 == 1 )
        puts "1"
    elsif ( rand(60)+1 == 0 )
        puts " - - 0 - -"
    end
end
=end

#est_time
=begin
20.times do
    num = (rand(12)+1) * 5
    puts num
end
=end
=begin
20.times do
    puts random_date.strftime('%a %b %d, %Y')
end
=end

# - = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - = - 
10.times do |index|

    o = [('a'..'z'), ('A'..'Z')].map(&:to_a).flatten
    email_name = (0...20).map { o[rand(o.length)] }.join
    
      
    User.create!({
          
        :email => "#{email_name}@gmail.com", 
        :password => "111111", 
        :password_confirmation => "111111",
          
        :username => names[ rand(names.length()) ],
        :name_first => names[ rand(names.length()) ],
        :name_last => names[ rand(names.length()) ],
         
    })
    
    
    # =>    Pantry Items
    temp_ingredients = ingredients[0..-1]
    # up to 500 items, minimum 50
    (rand(451) + 50).times do
        
        day = random_date()
        min = rand(5) + 1
        
        rand_ingred_index = rand(temp_ingredients.length())
        
        User.last.pantry_items.create!({ 
            
            :name => temp_ingredients[ rand_ingred_index ],
            :quantity => rand(20) + 1,
            :units => units[ rand(units.length()) ],
            :storage_bin => storage[ rand(storage.length()) ],
            :when_bought => day,
            :exp_date => day + rand(80),
            :min_item => min,
            :max_item => min + rand(12) + (rand(3) + 1)
        })
        
        temp_ingredients.delete_at(rand_ingred_index)
    end
    
    
    
    # =>    User Recipes
    rand(9).times do
        
        desc = ""
        temp_ingredients = ingredients[0..-1]
        
        (rand(10) + 4).times do
            desc += desc_array[ rand(desc_array.length()) ]
        end
        
        
        User.last.user_recipes.create!({ 
            
            :name => recipe[:names][ rand(recipe[:names].length()) ],
            :description => desc,
            :est_time => (rand(12)+1) * 5
        })


        # max 20 ingredients
        (rand(18) + 3).times do
        	
        	rand_ingred_index = rand(temp_ingredients.length())
        	
            User.last.user_recipes.last.ingredients.create!({
                
                :name => temp_ingredients[ rand_ingred_index ], 
                :amount => rand(15) + 1,
                :unit => units[ rand(units.length()) ]
            })
            
            temp_ingredients.delete_at(rand_ingred_index)
        end
        
        # max 20 instructions
        (rand(19) + 2).times do
            User.last.user_recipes.last.instructions.create!({
                
                :step => desc_array[ rand(desc_array.length()) ] + "."
            })
        end
    end
  
end